### ISSUE TITLE
Function in C file not generated if a typedef added in header file.

### ISSUE THREAD

**Issue by jamesrr39** [gotranspile/cxgo#86]
Hi,

It appears a function that is defined in C code is not generated if it is defined after an enum type definition. An example to reproduce:

`src/a.h`
```c
typedef enum {
    FIRST = 0
} X;

int a();
```

`src/a.c`
```c
#include "a.h"

int a() {
    return 1;
}
```

`cxgo.yml`
```yaml
root: ./src
out: ./out
package: out
use_go_int: true
files:
  - name: '*'
```

What is generated:
`out/a.go`
```go
package out

type X int

const FIRST X = 0
```
(a() function is not in generated Go code)

**Comment by dennwc** [comment]
It will work if you only process `*.c` files:

```yaml
files:
  - name: '*.c'
```

I guess it overrides the Go file with source generated from a `.h` after getting correct Go source from a `.c` file.

**Comment by jamesrr39** [comment]
Yes, you are correct that with `*.c`, the transpilation completes successfully. However, the problem both contain both the header and C file for this project, as  contents that I need.

I was able to work around it having the .h files in an include folder, and using the following `files` section in `cxgo.yml`:

```
files:
  - name: 'include/*.h'
  - name: '*.c'
```

This then creates Go files in the output directory, with files like `include_bbox.go` (for the include/bbox.h file) and `bbox.go` (for the bbox.c file), so that works.

However, of course it would be nice to have this working without the workaround :)

**Comment by dennwc** [comment]
@jamesrr39 It actually should work, as long as `.c` file includes `.h` file, cxgo should transpile all definitions into one Go file.

You can also do something like this, if for some reason this still doesn't work:
```yaml
files:
  - name: bbox.c   # overrides wildcard below
  - name: bbox.h
    go: bbox_h.go  # custom name for output Go file
  - name: *.c  # no special rules for other files
```
